### ISSUE TITLE
Enable to use Japanese characters

### ISSUE THREAD

**Issue by hideshi** [hideshi/pyagram#2]

**Comment by hideshi** [comment]
Solved by using pyparsing.Regex

**Comment by cm3** [comment]
Characters like " 。！？" are not included in the `string` variable in the lexical_analysis function. When I add those characters in `string` variable, I succeed to use those variable in a input file. But, I don't know what kind of characters should be excluded, in other words, I don't know appropriate solution for this problem. so I leave just a comment here. (When I set `string = pp.Regex('.+')`, output is white vacant png with no explicit error. So, some characters should be excluded, maybe.)

**Comment by cm3** [comment]
`string = pp.Regex('[^\]]+')` is enough?
